var timelineContentList = [
  {
    title_en: "Wal-Mart flag sales boom",
    title_es: "Spanish title",
    time_en: "Sept 12, 2001",
    time_es: "",
    body_en: "Wal-Mart reports selling 250,000 flags the day after the attack, 25 times more than a year before.",
    body_es: "Spanish body",
    rank: 3,
    link: "Commerce_2",
    caption_en: "American Flag on a home.",
    caption_es: "Spanish caption",
    image: "American_Flag_on_House_CC_BY_SA_Noah_Wulf.jpg",
    credit: "Noah Wulf",
  },
  {
    title_en: "Tragedy in Mesa, Arizona",
    title_es: "Spanish title",
    time_en: "Sept 15, 2001",
    time_es: "",
    body_en: "Sikh-American entrepreneur Balbir Singh Sodhi is murdered in broad daylight.",
    body_es: "Spanish body",
    rank: 2,
    link: "Islamophobia_4",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "Tragedy in Dallas",
    title_es: "Spanish title",
    time_en: "Sept 15, 2001",
    time_es: "",
    body_en: "Waqar Hasan and Vasudev Patel were killed in Dallas by a man seeking to “avenge” the United States. The murderer specifically targeted Arab Americans or people who looked to be of Muslim descent.",
    body_es: "Spanish body",
    rank: 2,
    link: "Islamophobia_4",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "Anti-Arab racism on the rise",
    title_es: "Spanish title",
    time_en: "Sept 16, 2001",
    time_es: "",
    body_en: "A series of polls reveals that over half of Americans support discriminatory security policies against Arabs and Arab Americans.",
    body_es: "Spanish body",
    rank: 2,
    link: "Islamophobia_2",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "9/11 Victim Compensation Fund established",
    title_es: "Spanish title",
    time_en: "Sept 22, 2001",
    time_es: "",
    body_en: "The fund will provide compensation to any individual who was physically injured as a result of the 9/11 attacks.",
    body_es: "Spanish body",
    rank: 2,
    link: "Health_3",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "President’s Surveillance Program authorized",
    title_es: "Spanish title",
    time_en: "Oct 4, 2001",
    time_es: "",
    body_en: "The PSP is a collection of secret intelligence activities launched by George W. Bush in the wake of 9/11, authorizing warrantless wiretapping.",
    body_es: "Spanish body",
    rank: 2,
    link: "PSP_1",
    caption_en: "Cover of declassified Report on the President’s Surveillance Program released July 10, 2009.",
    caption_es: "Spanish caption",
    image: "PSP_report.jpg",
    credit: "",
  },
  {
    title_en: "First 9/11 commemorative coin released",
    title_es: "Spanish title",
    time_en: "Oct 15, 2001",
    time_es: "",
    body_en: "The National Collector’s Mint announces the sale of their first 9/11 collectible coin a little over a month after the attacks. According to NCM, the coin quickly sold out.",
    body_es: "Spanish body",
    rank: 4,
    link: "",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "Patriot Act signed",
    title_es: "Spanish title",
    time_en: "Oct 26, 2001",
    time_es: "",
    body_en: "The Patriot Act is the first of many changes to surveillance laws that makes it easier for the U.S. government to spy on American citizens and indefinitely detain immigrants.",
    body_es: "Spanish body",
    rank: 1,
    link: "Patriot_act_1",
    caption_en: "President George W. Bush signs the Patriot Act.",
    caption_es: "Spanish caption",
    image: "President_George_W._Bush_Signs_Patriot_Act_Public_Domain.jpg",
    credit: "",
  },
  {
    title_en: "TSA established",
    title_es: "Spanish title",
    time_en: "Nov 19, 2001",
    time_es: "",
    body_en: "The TSA enhances airport security procedures and centralizes air travel under a single federal agency.",
    body_es: "Spanish body",
    rank: 1,
    link: "TSA_1",
    caption_en: "The official flag of the Transportation Security Administration.",
    caption_es: "Spanish caption",
    image: "TSA_flag.png",
    credit: "",
  },
  {
    title_en: "First <i>Tribute in Light</i>",
    title_es: "Spanish title",
    time_en: "Mar 11, 2002",
    time_es: "",
    body_en: "On the six-month anniversary of 9/11, <i>Tribute in Light</i> begins as a temporary commemorative display in honor of the victims.",
    body_es: "Spanish body",
    rank: 4,
    link: "Rebuilding_1",
    caption_en: "The official flag of the Transportation Security Administration.",
    caption_es: "Spanish caption",
    image: "Tribute_in_Light_CC_BY_Anthony_Quintano.jpg",
    credit: "Anthony Quintano",
  },
  {
    title_en: "Ground Zero design competition",
    title_es: "Spanish title",
    time_en: "Summer 2002",
    time_es: "",
    body_en: "The Lower Manhattan Development Corporation organizes a competition to determine how to use Ground Zero.",
    body_es: "Spanish body",
    rank: 4,
    link: "Rebuilding_3",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "Department of Homeland Security formed",
    title_es: "Spanish title",
    time_en: "Nov 25, 2002",
    time_es: "",
    body_en: "The Department of Homeland Security’s stated mission includes anti-terrorism, border security, immigration and customs, cyber security, and disaster prevention and management.",
    body_es: "Spanish body",
    rank: 2,
    link: "DHS_1",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "ACLU challenges National Security Letters",
    title_es: "Spanish title",
    time_en: "April 2004",
    time_es: "",
    body_en: "The ACLU files a lawsuit challenging the FBI's authority to demand records through NSLs. Parts of the NSL statute were later declared unconstitutional.",
    body_es: "Spanish body",
    rank: 4,
    link: "Patriot_act_4",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "Warrantless wiretapping revealed",
    title_es: "Spanish title",
    time_en: "Dec 16, 2005",
    time_es: "",
    body_en: "The New York Times publishes an article revealing that President Bush secretly authorized the NSA to eavesdrop on Americans without the court-approved warrants.",
    body_es: "Spanish body",
    rank: 3,
    link: "PSP_2",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "Transatlantic aircraft plot",
    title_es: "Spanish title",
    time_en: "2006",
    time_es: "",
    body_en: "A terrorist plot to detonate liquid explosives is discovered by British police. The plot leads the TSA to restrict liquids in carry-on luggage.",
    body_es: "Spanish body",
    rank: 3,
    link: "TSA_4",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: "Construction Begins on One World Trade Center",
    title_es: "Spanish title",
    time_en: "April 27, 2006",
    time_es: "",
    body_en: "The New York Times publishes an article revealing that President Bush secretly authorized the NSA to eavesdrop on Americans without the court-approved warrants.",
    body_es: "Spanish body",
    rank: 4,
    link: "Rebuilding_3",
    caption_en: "One World Trade Center tower construction in 2007.",
    caption_es: "Spanish caption",
    image: "Freedom_Tower_August_7th_2007_Public_Domain.jpg",
    credit: "",
  },
  {
    title_en: `“Six Flying Imams” incident`,
    title_es: "Spanish title",
    time_en: "April 27, 2006",
    time_es: "",
    body_en: "Six Muslim imams are removed from a flight because their prayer alarms several passengers and crew members. They are arrested, questioned, and held for three hours before being released.",
    body_es: "Spanish body",
    rank: 2,
    link: "",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: `SPOT program implemented`,
    title_es: "Spanish title",
    time_en: "2007",
    time_es: "",
    body_en: "The Screening of Passengers by Observation Techniques program uses 94 criteria to identify potential terrorists. ",
    body_es: "Spanish body",
    rank: 3,
    link: "TSA_4",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: `Protect America Act of 2007 signed`,
    title_es: "Spanish title",
    time_en: "Aug 5, 2007",
    time_es: "",
    body_en: "The act removes the warrant requirement for government surveillance on targets believed to be outside the United States.",
    body_es: "Spanish body",
    rank: 4,
    link: "",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
  {
    title_en: `9/11 Memorial dedication ceremony`,
    title_es: "Spanish title",
    time_en: "Sept 11, 2011",
    time_es: "",
    body_en: "A dedication ceremony commemorating the tenth anniversary of the attacks is held at the memorial, which opens to the public the following day.",
    body_es: "Spanish body",
    rank: 2,
    link: "",
    caption_en: "One of the 9/11 Memorial fountains inscribed with the victims’ names.",
    caption_es: "Spanish caption",
    image: "National_september_11_Memorial_&_museum_CC_BY_SA_Saschaporsche.jpg",
    credit: "Wikipedia user Saschaporsche",
  },
  {
    title_en: `One World Trade opens`,
    title_es: "Spanish title",
    time_en: "Nov 3, 2014",
    time_es: "",
    body_en: "With a spire reaching 1,776 feet, the building is taller than the old 1 WTC.",
    body_es: "Spanish body",
    rank: 1,
    link: "Rebuilding_3",
    caption_en: "One World Trade Center as seen from New Jersey.",
    caption_es: "Spanish caption",
    image: "New_1WTC_CC_BY_SA_ King_of_Hearts.jpg",
    credit: "Wikipedia user King of Hearts",
  },
  {
    title_en: `VCF Permanent Authorization Act signed`,
    title_es: "Spanish title",
    time_en: "July 29, 2019",
    time_es: "",
    body_en: "The Act, signed by President Trump, extends the filing deadline for the Victims Compensation Fund to 2090, ensuring that 9/11 victims and first responders could continue to receive financial support for their 9/11 related illnesses.",
    body_es: "Spanish body",
    rank: 2,
    link: "Health_4",
    caption_en: "President Donald Trump signs permanent authorization for the Victim Compensation Fund.",
    caption_es: "Spanish caption",
    image: "Trump_signs_VCF_Public_Domain.jpg",
    credit: "",
  },
  {
    title_en: `Patriot Act expires`,
    title_es: "Spanish title",
    time_en: "Mar 15, 2020",
    time_es: "",
    body_en: `As of September 2021, it has not been reauthorized.`,
    body_es: "Spanish body",
    rank: 2,
    link: "",
    caption_en: "",
    caption_es: "Spanish caption",
    image: "",
    credit: "",
  },
];

var bodyContentList = [
  {
    id: "Patriotism_1",
    header_en: "Patriotism and Dissent After 9/11",
    header_es: "Spanish header",
    body_en: "Shortly following the attacks on the Pentagon and World Trade Center, America entered an immediate and sustained period of collective grief. Central to post-9/11 mourning was an increase in expressions of patriotic symbolism. People across the country hung American flags in their windows and on their porches in a sign of national solidarity.",
    body_es: "Spanish body"
  },
  {
    id: "Patriotism_2",
    body_en: `A wave of patriotic songs, paintings, essays, and poetry began to spread across American media. These works expressed sorrow for the victims and a belief that the tragedy would make America stronger. Author Diana Hoffman’s 2002 poem, “The Power of Freedom,” expressed this sentiment, writing “You’ve galvanized our nation into a force so strong. We’ll end your reign of terror although the fight is long.” In 2001, country music artist Toby Keith recorded his popular “Courtesy of the Red, White and Blue,” a patriotic anthem centered around the theme of retribution. “And you'll be sorry that you messed with The U.S. of A,” Keith famously sang, “Cause we'll put a boot in your ass. It's the American way.”`,
    body_es: "Spanish body"
  },
  {
    id: "Patriotism_3",
    body_en: `Conversely, dissent was harshly criticized and often silenced. American writer and political activist, Susan Sontag, received backlash after writing in the New Yorker, “Where is the acknowledgement that this was not a ‘cowardly’ attack on ’civilization’ or ’liberty’ or ‘humanity’ or ‘the free world’ but an attack on the world's self-proclaimed super-power, undertaken as a consequence of specific American alliances and actions?”`,
    body_es: "Spanish body"
  },
  {
    id: "Patriotism_4",
    body_en: `Her article was vilified by the media. Columnist Charles Krauthammer lambasted Sontag as “morally obtuse,” and historian and journalist Richard Brookhiser called her article “shameful,” compared her to Osama bin Laden, and described her as the “the harbinger of the ‘we deserved it’ school of thought.” In a similar fashion, the band, “The Dixie Chicks” were blacklisted from country music radio stations across the U.S. after they publicly criticized George W. Bush’s actions in the Middle East.`,
    body_es: "Spanish body"
  },
  {
    id: "Commerce_1",
    header_en: "The Commercialization of Tragedy",
    header_es: "Spanish header",
    body_en: `The outpouring of patriotic zeal mirrored a wave of 9/11 memorabilia. Before the rubble even settled, consumers were presented with an abundance of patriotic merchandise to entice them. From “Never Forget” bumper stickers to a seemingly limitless supply of American flag t-shirts, many Americans sought to express their solidarity with the victims through their purchases.`,
    body_es: "Spanish body"
  },
  {
    id: "Commerce_2",
    body_en: "Wal-Mart sold 116,000 American flags on the day of the attacks. On the following day, they sold 250,000 more. By comparison, Wal-Mart sold 6,400 and 10,000 on the same days a year earlier. Numerous other stores also reported a dramatic increase in flag sales.",
    body_es: "Spanish body"
  },
  {
    id: "Commerce_3",
    body_en: "Many Americans criticized the flood of memorabilia as overly sentimental, or even tasteless, often accusing companies of capitalizing on tragedy. The 9/11 Memorial and Museum in New York City received extensive criticism after its opening in 2014. Museum-goers reported being taken aback by their gift shop, which sold, among other items, 9/11 stuffed animals, bottles of 9/11 memorial wine, and a 9/11-themed commemorative cheese plate.",
    body_es: "Spanish body"
  },
  {
    id: "Commerce_4",
    body_en: "Several companies also attempted to use 9/11 as a marketing tactic. In 2016, a mattress store in San Antonio received national outrage after advertising a “Twin Towers sale,” where consumers could “get any sized mattress for a twin price,” before toppling two piles of mattresses. The same year, a Wal-Mart in Florida got backlash after setting up a 9/11 promotional display made of Coke boxes in the shape of the Twin Towers.",
    body_es: "Spanish body"
  },
  {
    id: "Islamophobia_1",
    header_en: "Islamophobia and Anti-Arab Racism",
    header_es: "Spanish header",
    body_en: "In the weeks and months following 9/11, Arab Americans and Muslim Americans often became targets of violence, racial profiling, surveillance, and even deportation. Although Islamophobia existed prior to 2001, 9/11 suddenly made Muslim Americans and Arab Americans a highly visible community.",
    body_es: "Spanish body"
  },
  {
    id: "Islamophobia_2",
    body_en: "A series of polls released shortly after the attacks revealed that many Americans held harsh views of Arabs and Arab Americans. A Newsweek poll conducted on September 13, 2001 found that 32% of respondents believed that Arab Americans should be put under special surveillance and required to carry special documentation. Three days later, a Gallup Poll revealed that nearly 60% of Americans were willing to support increased security measures aimed specifically at Arabs and Arab Americans in the United States.",
    body_es: "Spanish body"
  },
  {
    id: "Islamophobia_3",
    body_en: `Growing hostility was also reflected in American immigration policy. After the passage of the Patriot Act, new security policies targeted specific immigrant communities. One of the earliest post-9/11 security initiatives was a targeted round-up of more than 1,200 Arab and Muslim individuals who did not hold legal immigration status. This and other efforts targeted people on the basis of religion and national origin, not conduct. As a result of these actions, Muslim and Arab communities have reported being increasingly hesitant about contacting the police.`,
    body_es: "Spanish body"
  },
  {
    id: "Islamophobia_4",
    body_en: `This happened at a time when these communities needed police protection more than ever. They were often targets of hate crimes immediately following the 9/11 attacks. These included acts of violence against mosques, Arab American-owned businesses, individual Muslims, and people perceived to be Muslims. In the following weeks, Waqar Hasan, a Muslim born in Pakistan, and Vasudev Patel, an Indian immigrant who was Hindu, were gunned down in Dallas. The killer stated that he did it to “avenge" the United States for 9/11. Sikh-American entrepreneur Balbir Singh Sodhi was murdered in Mesa, Arizona. Upon his arrest, the killer told the police, “I am a patriot! I stand for America!” These murders were not isolated incidents. According to FBI data, hate crimes against Muslims rose more than 1,600% following 9/11.`,
    body_es: "Spanish body"
  },
  {
    id: "Islamophobia_5",
    body_en: `Anti-Arab racism and Islamophobia continues to persist throughout the United States. A 2016 study found 174 incidents of anti-Muslim violence and vandalism, including 12 murders and 54 acts of vandalism or destruction of property.`,
    body_es: "Spanish body"
  },
  {
    id: "Islamophobia_6",
    body_en: "Islamophobia also persists locally. In 2014, a member of the Keller School Board wrote, “YOU NOW HAVE A ‘MUSLIM’ on the City Council!!! WHAT A SHAME!!!!!” In 2017, 14-year-old Ahmed Mohamed, a ninth-grader from Irving was arrested after bringing a homemade clock to school, under the presumption that the clock was a bomb.",
    body_es: "Spanish body"
  },
  {
    id: "Patriot_act_1",
    header_en: `The Surveillance State`,
    header_es: "Spanish header",
    body_en: `<H2>The Patriot Act</H2>While Operation Enduring Freedom swept Afghanistan, Americans experienced the War on Terror on the home-front. 45 days following the attacks, President Bush signed the Patriot Act into law, easing restrictions on intelligence gathering. It gave law enforcement agencies the authority to wiretap telephones, monitor email messages, and freely search records of individuals suspected of terrorism.`,
    body_es: "Spanish body"
  },
  {
    id: "Patriot_act_2",
    body_en: "The Department of Justice believes that the Patriot Act greatly improved U.S. counterterrorism efforts. It allowed federal agents to disrupt potential threats, dismantle terrorist funding networks, use more sophisticated surveillance techniques, and obtain business records in national security terrorism cases. The act also facilitated information sharing between government agencies and law enforcement. Government officials argue that many acts of terrorism, including 9/11, could have been prevented with simpler communication between the CIA, FBI, and other intelligence or law enforcement agencies.",
    body_es: "Spanish body"
  },
  {
    id: "Patriot_act_3",
    body_en: "While the act has given law enforcement agencies more tools to prevent terrorism, it has also been criticized as giving the government unchecked power to look through the records of American citizens. Opponents of the act argue that these measures violate the Fourth Amendment to the Constitution, which prohibits unreasonable search and seizure. Supporters of the act, however, argue that these measures do not violate the Constitution and are necessary to prevent future acts of terrorism.",
    body_es: "Spanish body"
  },
  {
    id: "Patriot_act_4",
    body_en: "Central to many critiques of the Patriot Act is the expansion of National Security Letters (NSLs). NSLs allowed FBI investigators to gather large amounts of information on Americans without prior approval from a judge. The Justice Department's Inspector General reported that between 2003 and 2006, the FBI issued nearly 200,000 NSLs. Of these, only 53 led to criminal investigations and none were linked to acts of terrorism. The use of NSLs was later challenged in court.",
    body_es: "Spanish body"
  },
  {
    id: "Patriot_act_5",
    body_en: `The Patriot Act also allowed federal law enforcement agencies to issue “Sneak and Peek” warrants, otherwise known as delayed notice warrants. These warrants enable investigators to enter a home while the occupant is away, search their property, and not alert them until after the fact. In 2010, 3,970 “Sneak and Peek” warrants were issued. Less than 1% were linked to terrorism-related crimes. The vast majority—over 75%—were linked to drug-related offenses.`,
    body_es: "Spanish body"
  },
  {
    id: "Patriot_act_6",
    body_en: `Americans remain divided over the efficacy of the Patriot Act. In 2004, a poll revealed that 33% of Americans believe the Patriot Act to be a necessary tool that helps the government find terrorists, while 39% believed the act goes too far and poses a threat to civil liberties. By 2011, poll results shifted somewhat in its favor, with 42% believing it to be necessary, and 34% believing it goes too far.`,
    body_es: "Spanish body"
  },
  {
    id: "Patriot_act_7",
    body_en: `After several reauthorizations, the Patriot Act expired on March 15, 2020. As of September 2021, it has not been reauthorized.`,
    body_es: "Spanish body"
  },
  {
    id: "PSP_1",
    body_en: `<H2>The President’s Surveillance Program</H2>The Patriot Act was far from the only sweeping change to American security policy in reaction to 9/11. Shortly following the attacks, President Bush authorized the President’s Surveillance Program (PSP). The PSP authorized the National Security Agency to collect certain communications data in an effort to prevent terrorism.`,
    body_es: "Spanish body"
  },
  {
    id: "PSP_2",
    body_en: `Central to the PSP was the Terrorist Surveillance Program, which was responsible for intercepting communications with members of al-Qaeda or groups affiliated with al-Qaeda. In 2005, the New York Times revealed that the Bush administration had been conducting warrantless electronic surveillance of Americans’ communications for four years, sometimes unrelated to al-Qaed. In response, President Bush argued that the Authorization for Use of Military Force of 2001 implicitly authorized warrantless surveillance in these circumstances. The NSA has been sued by multiple organizations over warrantless wiretapping. It came under further fire in 2013 after Edward Snowden, a computer intelligence consultant and former CIA employee, released classified NSA documents that revealed a larger, global surveillance network.`,
    body_es: "Spanish body"
  },
  {
    id: "TSA_1",
    body_en: `<H2>The TSA</H2>On November 19, 2001, Congress passed the Aviation and Transportation Security Act (ATSA). The ATSA gave the federal government direct responsibility for airport screenings and created the Transportation Security Administration, also known as the TSA.`,
    body_es: "Spanish body"
  },
  {
    id: "TSA_2",
    body_en: `Before 9/11, airport security was shared between airport authorities and commercial airlines. In most cases, security screenings only looked for major weapons, like handguns and bombs. Travelers were generally able to carry baseball bats, scissors, and blades up to 4-inches in length. Airport security often consisted of simple metal detectors. Guests were usually allowed to accompany travelers all the way to their departure gate.`,
    body_es: "Spanish body"
  },
  {
    id: "TSA_3",
    body_en: `Following 9/11, the TSA implemented enhanced security procedures. Today, most airports in the U.S. use full-body scanning machines to detect weapons. The TSA also performs pat-downs, restricts certain devices, checks identification, screens for explosives, and only allows ticketed passengers to go to the gate.`,
    body_es: "Spanish body"
  },
  {
    id: "TSA_4",
    body_en: `Enhanced security measures did not end there. In 2006, airports banned liquids above 3.5 oz in carry-on luggage in response to a liquid bomb plot. In 2007, the TSA implemented the SPOT (Screening of Passengers by Observation Techniques) program. The program trains TSA agents to identify potential terrorists by looking for signs for either stress, fear, or deception. The program has been critiqued as pseudoscientific. It has also been accused of leading to racial profiling.`,
    body_es: "Spanish body"
  },
  {
    id: "DHS_1",
    body_en: `<H2>The Department of Homeland Security</H2>On November 25, 2002, Congress established the Department of Homeland Security (DHS) in response to the attacks. The Department’s stated goals include cyber security, anti-terrorism, border security, immigration and customs, and disaster prevention. A number of agencies fall under the Department, including the U.S. Customs and Border Protection, U.S. Immigration and Customs Enforcement (ICE), and the Secret Service. The DHS also absorbed the TSA.`,
    body_es: "Spanish body"
  },
  {
    id: "Rebuilding_1",
    header_en: `Rebuilding and Commemorating`,
    header_es: "Spanish header",
    body_en: `In the days and weeks following 9/11, communities throughout the United States held ceremonies, candlelight vigils, and marches to memorialize the 2,977 who were killed. Designers worked on commemorative pieces to honor the victims. Spontaneous memorials appeared in New York City. The first major memorial art installation was <i>Tribute in Light</i>, first displayed in March 2002. The installation is made up of vertical searchlights arranged in two columns to represent the Twin Towers. <i>Tribute in Light</i> is reignited every year on the anniversary of September 11.`,
    body_es: "Spanish body"
  },
  {
    id: "Rebuilding_2",
    body_en: `<H2>The National September 11 Memorial</H2>Five years after the attacks, construction began on the National September 11 Memorial, located on the former site of the World Trade Center. On the 10th anniversary of the attacks, the memorial was dedicated, and it opened to the public the following day. The memorial consists of two reflective pools with the victims’ names inscribed on the side. It also includes the names of the six individuals killed in the 1993 World Trade Center bombing.`,
    body_es: "Spanish body"
  },
  {
    id: "Rebuilding_3",
    body_en: `<H2>One World Trade Center</H2>Almost immediately after September 11, New York City planners began considering proposals for a World Trade Center replacement. In the summer of 2002, a design competition was launched to replace the fallen towers. The winning building design was announced in early 2003, though the original design underwent several modifications. The final design was unveiled on June 28, 2005 and construction began less than a year later. The building officially opened on November 3, 2014 as Condé Nast, a New York based publishing company, became the building’s first occupant. On May 29, 2015, the One World Trade observatory opened to the public, offering a view of the city at 1,250 feet.`,
    body_es: "Spanish body"
  },
  {
    id: "Rebuilding_4",
    body_en: `Today, One World Trade stands at 1,776 feet tall (including the tower’s spire). The height was purposefully chosen in honor of 1776, the year the Declaration of Independence was signed. With the spire included in the building's height, One World Trade is currently the tallest building in the United States and the sixth-tallest building in the world.`,
    body_es: "Spanish body"
  },
  {
    id: "Health_1",
    header_en: `Rebuilding and Commemorating`,
    header_es: "Spanish header",
    body_en: `Within seconds of the attacks, debris spewed from the World Trade Center, coating lower Manhattan in a thick film of toxic dust. Exposure to the debris has led to debilitating, ongoing illnesses among New Yorkers closest to the attacks. These include upper respiratory illnesses, certain cancers, hearing loss, and stroke. On top of the physical ailments, those who witnessed and responded to the attacks experience higher rates of mental illness, including post-traumatic stress disorder (PTSD), depression, alcoholism, and other forms of substance abuse.`,
    body_es: "Spanish body"
  },
  {
    id: "Health_2",
    body_en: `These ailments hit no one harder than the rescue, recovery, and cleanup workers who responded to the attacks. Increasing numbers of first responders are developing serious respiratory ailments, prostate cancer, thyroid cancer, and multiple myeloma.`,
    body_es: "Spanish body"
  },
  {
    id: "Health_3",
    body_en: `In response to the growing health concerns associated with 9/11, Congress quickly passed the Victim Compensation Fund (VCF) in 2001. The VCF provides medical assistance to those most affected by the attacks. This fund initially closed in 2004. Due to the nature of many of these illnesses, the 2004 cutoff proved to be a problem for those with lingering health conditions.`,
    body_es: "Spanish body"
  },
  {
    id: "Health_4",
    body_en: `In 2011, Congress passed the Zadroga Act, which authorized the Victim Compensation Fund to operate for an additional period of five years. In 2015, President Obama signed a new bill into law that reauthorized the Zadroga Act, extending the VCF through 2020. And, on July 29, 2019, President Trump signed into law H.R. 1327, The Never Forget the Heroes Act, also known as the VCF Permanent Authorization Act. The Act extends the VCF’s claim filing deadline from December 18, 2020, to October 1, 2090. The act appropriates all necessary funds to pay out the victims’ claims in perpetuity.`,
    body_es: "Spanish body"
  },
]
